### ISSUE TITLE
Non-standard header?

### ISSUE THREAD

**Issue by iconara** [komiya-atsushi/lz4-ruby#3]
I tried using lz4-ruby to implement compression in my Cassandra driver, [cql-rb](https://github.com/iconara/cql-rb/). Cassandra supports LZ4 compression of requests and responses, but lz4-ruby can't decompress the messages coming from Cassandra because it expects the message to have a header.

Is this header a standard LZ4 thing, or is it something you've added just to be able to use the faster decompression methods?

**Comment by komiya-atsushi** [comment]
> Is this header a standard LZ4 thing, 

No, it isn't.
Lz4-ruby appends original string length information in front of LZ4 string.

I'm planning to add some new APIs for handling raw LZ4 string.

**Comment by iconara** [comment]
It would be great to be able to use lz4-ruby to decompress things produced by other systems that support LZ4. I very much want to add LZ4 support to cql-rb.

**Comment by komiya-atsushi** [comment]
From version 0.3.1, `lz4-ruby` supports raw data handling methods ( `LZ4::Raw` ).
