### ISSUE TITLE
LZ4 compression changes string encoding

### ISSUE THREAD

**Issue by rcarvalho** [komiya-atsushi/lz4-ruby#6]
Here is the following commands in irb that reproduce this issue. Why does my UTF8 encoded string turn into an ASCII string? When I uncompress it, it will remain ASCII. But, that is not my original string. Because of this conversion that takes place I actually lose some of my UTF8 data.

1.9.3-p484 :003 > t = "teststring"
 => "teststring"
1.9.3-p484 :004 > t.encoding
 => #Encoding:UTF-8
1.9.3-p484 :005 > require 'lz4-ruby'
 => true
1.9.3-p484 :006 > result = LZ4::compress t
 => "\n\xA0teststring"
1.9.3-p484 :007 > result.encoding
 => #Encoding:ASCII-8BIT

**Comment by iconara** [comment]
I don't agree that this is a bug. There is no way for the compression library to know what encoding the string was before it was compressed. To the compression library it is just a byte array, and the output is a byte array. Ruby's string encodings are not part of the byte representation of strings, and this is true for most languages (but some have only support for a single encoding of strings – like Java and UTF-16, and there you don't notice this, Ruby is much more flexible when it comes to encodings, but on the other hand you get situations like this).

It's unfortunate that `decompress(compress(str)).encoding != str.encoding`, but achieving this is impossible without adding extra data to the compressed string, which would be non-standard and non-portable. You wouldn't be able to compress a string in Ruby and read it in C or Java, for example.

The workaround is to re-tag the string when it is decompressed:

``` ruby
str = LZ4.uncompress(bytes)
str.force_encoding(Encoding::UTF_8)
```

Btw. I think your example is missing the last part, you're only showing that the encoding of the compressed data is binary, which should be expected in all circumstances, what I assume you meant was that if you add

``` ruby
str = LZ4.uncompress(result)
str.encoding # => #Encoding::ASCII-8BIT
```

**Comment by rcarvalho** [comment]
Thanks for the response. That makes sense. I actually tested this with ZLib and it works the same way. My only concern was that when I tried to do a force encoding back to UTF8 that there would potentially be characters that didn't translate well and that I would lose some data. And, my application requires that my string into compression equals my string out of compression exactly. I have done a little testing and it seems ok. I will continue to do more testing on this.

**Comment by iconara** [comment]
The decompressed string will be byte-for-byte identical with the string you compressed, it's just that in Ruby strings have additional metadata that says which encoding the string should be interpreted as being in, and unless this metadata is the same, two strings with the same bytes will not be equal when compared with `==`. They will still have the same bytes, and if you call `#force_encoding` to re-tag the decompressed string with its proper encoding it will again be equal to the string you compressed.

`#force_encoding` does not change the bytes, just the encoding metadata (`#encode` on the other hand changes the bytes, which you _don't_ want to do).

**Comment by rcarvalho** [comment]
Thanks for the clarification on force_encoding vs encode. I'm realizing that was probably my mistake the first time was that I was using encode and I was trying to encode to UTF8. I was getting exceptions with invalid character sequences. But, now that makes sense. It was trying to encode from ASCII to UTF8 even though the string was actually UTF8, but had the wrong metadata attached to it.
