### ISSUE TITLE
Security fix for 32-bits systems

### ISSUE THREAD

**Issue by Cyan4973** [komiya-atsushi/lz4-ruby#9]
Hi Komiya

There is a new security fix for 32-bits system available at : 
https://github.com/Cyan4973/lz4/releases/latest

The issue affects programs accepting very large data blocks in 32-bits mode.

As a security measure, all binders are invited to upgrade their underlying C source code to latest version.

Regards

**Comment by komiya-atsushi** [comment]
Now, I have released lz4-ruby 0.3.3 which uses the latest version of LZ4 (r119).

Also, it contains a work of LZ4 API migration (replacing deprecated function calls).

http://rubygems.org/gems/lz4-ruby/versions/0.3.3

**Comment by Cyan4973** [comment]
great , thanks !
